# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GhosttyGhost < Formula
  desc "A tool to convert terminal configs to Ghostty"
  homepage "https://github.com/gambithunt/ghostty-ghost"
  version "1.0.8"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/gambithunt/ghostty-ghost/releases/download/v1.0.8/ghostty-ghost_darwin_amd64.tar.gz"
      sha256 "1cc73f28ecfb8ace06966b1d793fcf24af1b309645b114fa096867f8933c81f0"

      def install
        bin.install "ghostty-ghost"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/gambithunt/ghostty-ghost/releases/download/v1.0.8/ghostty-ghost_darwin_arm64.tar.gz"
      sha256 "800a9bc7a08f556f855a8c5d7f939fba6a6c40054148baaeb66cffb85c08c8da"

      def install
        bin.install "ghostty-ghost"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/gambithunt/ghostty-ghost/releases/download/v1.0.8/ghostty-ghost_linux_amd64.tar.gz"
        sha256 "cae1d08d58d1e138aba6b6c33b3911911d3d7f85d017dc1e4432be31172d1adf"

        def install
          bin.install "ghostty-ghost"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/gambithunt/ghostty-ghost/releases/download/v1.0.8/ghostty-ghost_linux_arm64.tar.gz"
        sha256 "febc1b4ee64ceb57d95604d8805c64efb8d1d2dfde588a94bc797e80975c8bfb"

        def install
          bin.install "ghostty-ghost"
        end
      end
    end
  end

  test do
    system "#{bin}/ghostty-ghost --version"
  end
end
